insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_FROM','Email for send mail','plazaproveedor@inmobile.pe',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','PASSWORD_FROM','Password for send mail','Plaza2015',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','SUBJECT_CREATION_USER','Subject Creation User for send mail','InMobile - Creation User',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','SUBJECT_FINAL_STEP_USER','Subject for Final Step Registration','InMobile - Final Step Registration',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_TRUE','Configuration Email ','true',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_SMTP_GMAIL','Configuration Value for Send Email SMTP','smtp.gmail.com',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','EMAIL_PORT_GMAIL','Configuration Value for Send Email PORT','587',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','BODY_EMAIL_CREATION_USER','Texto para enviar en el correo',"<html><body><p><b>InMobile Activar Cuenta - Test Email</b></p><br/><p>Estimo Usario:</p><br/><p>Se ha registrado correctamente como usuario en la aplication</p><p>&#191;C&#243;mo funciona nuestro portal?</p><p><b>Continuar</b>Tiene que dar click en el enlace, para continuar con su registro (Enlace de Prueba)</p><a href='${URL}'>Aceptar</a><p><b>Rechazar</b>Tiene que dar click en el enlace, para rechazar y no recivir información sobre nosotros.(Enlace de Prueba)</p><a href='#'>Rechazar</a></body></html>",1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','BODY_EMAIL_ACTIVATION_USER','Texto para reenviar un nuevo enlace al cliente',"<html><body><p><b>InMobile Informa - Test Email</b></p><br/><p>Estimo Usario:</p><br/><p>Se ha adjuntado un nuevo enlace para continuar su proceso de Activación</p><p>&#191;C&#243;mo funciona nuestro portal?</p><p><b>Continuar</b>Tiene que dar click en el enlace, para continuar con su registro (Enlace de Prueba)</p><a href='${URL}'>Aceptar</a><p><b>Rechazar</b>Tiene que dar click en el enlace, para rechazar y no recivir información sobre nosotros.(Enlace de Prueba)<</p><a href='#'>Rechazar</a></body></html>",1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','BODY_EMAIL_FINAL_STEP_USER','Texto para confirmar el paso final del cliente',"<html><body><p><b>InMobile Registro de Cuenta - Test Email</b></p><br/><p>Estimo Usario:</p><br/><p>Su información esta siendo verificada por nuestro personal, de tener alguna duda nos pondremos en contacto con Ud.</p><p><b>Gracias</b></p><br/><p><b>Atte.</b></p><br/><p><b>Plaza Proveedor</b></p><br/></body></html>",1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','BODY_EMAIL_COMPLETE_BY_ADMIN','Texto para notificar que la cuenta ya esta de alta',"<html><body><p><b>InMobile la cuenta esta Activada</b></p><br/><p>Estimo Usario:</p><br/><p>El administrado ha verificado la informacion ingresada.</p><p>Su cuenta ya esta lista.</p><p><b>Gracias</b></p><br/><p><b>Atte.</b></p><br/><p><b>Plaza Proveedor</b></p><br/></body></html>",1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('EMAIL','SUBJECT_COMPLETE_BY_ADMIN','Subject for final Activation','InMobile - Account is Ready',1);

insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('SERVICE','URL_SERVER','URL from the server','http://localhost:8080/',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('SERVICE','PROJECT_VALUE','Name of the project','InMobileWeb/',1);
insert into tb_system_param (generalParam,nameParam,reasonParam,valueParam,status) values ('SERVICE','ACTION_CONTINUE','Name of the action','continue.htm?val=',1);
